spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/to-do
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
  error:
    include-message: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem